#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off 

pgrep -x picom >/dev/null || picom --backend xrender --config "$HOME/.config/picom/picom.conf" &
command -v vmware-user >/dev/null 2>&1 && vmware-user &
command -v clipmenud >/dev/null 2>&1 && clipmenud &

# VMware / resolución automática
command -v vmware-user >/dev/null 2>&1 && pgrep -x vmware-user >/dev/null || vmware-user &

xrandr --auto &

# Wallpaper
feh --bg-fill /usr/share/wallpapers/desktop_geminis.png &

# Polybar
~/.config/polybar/launch.sh &

# Vigilar cambios de resolución y reajustar wallpaper/polybar
while true; do
    CURRENT_RES="$(xrandr | grep '*' | head -n1)"

    if [ "$CURRENT_RES" != "$LAST_RES" ]; then
        LAST_RES="$CURRENT_RES"
        feh --bg-fill /usr/share/wallpapers/desktop_geminis.png &
        ~/.config/polybar/launch.sh &
    fi

    sleep 2
done &
