#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off 

picom &
command -v vmware-user >/dev/null 2>&1 && vmware-user &
command -v clipmenud >/dev/null 2>&1 && clipmenud &
xrandr | grep -q "Virtual-1 connected" && xrandr --output Virtual-1 --mode 1920x1080 &
~/.config/polybar/launch.sh &

# Iniciar el recolector de cliphist (necesita wl-paste en Wayland o un agente de X11)
# Si estás en X11 (lo más probable en bspwm):
# O directamente el comando de cliphist si usas un script de captura:
# (Esto depende de qué herramienta uses para capturar el copy)
#
feh --bg-scale /usr/share/wallpapers/desktop_geminis.png

# Set resolution

