[colors]
; Colores extraídos de la estética de la imagen
bg = #1a1b26
bg-alt = #24283b
fg = #c0caf5
blue = #7aa2f7
green = #9ece6a
magenta = #bb9af7
red = #f7768e
gray = #414868
sep = #414868
violet = #CBA6F7
pink = #F5BDE6

[bar/main]
width = 98%
height = 32
offset-x = 1%
offset-y = 8
radius = 12
fixed-center = true

background = ${colors.bg}
foreground = ${colors.fg}

line-size = 0
border-size = 1
border-color = #CBA6F7

padding-left = 1
padding-right = 1

module-margin = 0

; Asegúrate de tener instalada una Nerd Font (ej. JetBrainsMono Nerd Font)
font-0 = "MesloLGS NF:size=11;2"
font-1 = "MesloLGS NF:size=11;2"

wm-restack = bspwm
enable-ipc = true

modules-left = myip sep vpn sep htb
modules-center = bspwm
modules-right = music sep menu sep cpu sep date sep power

cursor-click = pointer

[module/sep]
type = custom/text
content = "|"
content-foreground = ${colors.sep}
content-padding = 1

# --- MÓDULOS IZQUIERDA ---

[module/myip]
type = custom/script
exec = ~/.config/polybar/scripts/ip_local
interval = 10
format = <label>
format-prefix = 
format-prefix-foreground = ${colors.blue}
format-background = ${colors.bg-alt}
format-padding = 1

[module/vpn]
type = custom/script
exec = ~/.config/polybar/scripts/ip_vpn
interval = 2
format = <label>
format-background = ${colors.bg-alt}
format-padding = 1

[module/htb]
type = custom/script
exec = ~/.config/polybar/scripts/target_htb
interval = 2
format = <label>
format-prefix =  
format-prefix-foreground = ${colors.magenta}
format-background = ${colors.bg-alt}
format-padding = 1
click-left = ~/.config/polybar/scripts/copy_ip

# --- MÓDULOS CENTRO (BSPWM) ---

[module/bspwm]
type = internal/bspwm
format = <label-state>
format-background = ${colors.bg-alt}
format-padding = 2

label-focused = %index%
label-focused-padding = 1
label-focused-foreground = ${colors.pink}


label-occupied = %index%
label-occupied-foreground = ${colors.fg}
label-occupied-padding = 1

label-empty = %index%
label-empty-foreground = ${colors.gray}
label-empty-padding = 1

# --- MÓDULOS DERECHA ---

[module/music]
type = custom/script
exec = playerctl metadata --format "{{ title }}" 2>/dev/null || echo "   moon   " 
interval = 1 
format = <label>
format-prefix = "󰝚 "
format-prefix-foreground = ${colors.red}
format-background = ${colors.bg-alt}
format-padding = 2

label-maxlen = 25
label-ellipsis = true 

click-left = ~/.config/polybar/scripts/toggle-now-playing.sh


[module/menu]
type = custom/text
content = "󰑣"
content-foreground = ${colors.fg}
content-background = ${colors.bg-alt}
content-padding = 1
click-left = rofi -show drun


[module/cpu]
type = custom/text
content = "≡"
content-foreground = ${colors.fg}
content-background = ${colors.bg-alt}
content-padding = 1
click-left = eww open --toggle control_center

[module/date]
type = internal/date
interval = 1
date = %a %d %b
time = %H:%M
format = <label>
format-prefix = "󰃭 "
format-prefix-foreground = ${colors.gray}
format-background = ${colors.bg-alt}
format-padding = 1
;; Lo mismo para la fecha
label = %{A1:eww open --toggle calendar_window:}%date% | %time%%{A}


[module/power]
type = custom/text
content = "⏻"
content-foreground = ${colors.red}
content-background = ${colors.bg-alt}
content-padding = 1
click-left = ~/.config/polybar/scripts/powermenu/powermenu.sh
