#!/usr/bin/env bash

if ip link show tun0 >/dev/null 2>&1; then
    if ip a show tun0 | grep -q "inet "; then
        ip_vpn=$(ip a show tun0 | awk '/inet / {print $2}' | cut -d/ -f1)
        echo "%{F#1bbf3e}󰆧%{F#ffffff}$ip_vpn"
    else
        echo "%{F#e51d0b}󰆧%{F#ffffff}Disconnected"
    fi
else
    echo "%{F#e51d0b}󰆧 %{F#ffffff}Disconnected"
fi
